name: shell-command
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo-a-string
        run: echo "Hello world"
      - name: multilined-script
        run: |
          node -v
          npm -v
